"""Shared menu layout and label normalization for the bot UI."""

USER_BASE_MENU_ROWS = [
    ["✅ Tekshiruv", "� Tarjima"],
    ["🔊 Talaffuz", "🎯 Quiz"],
    ["� IQ Test", "📚 Dars"],
    ["� Gramматика", "📅 Kunlik so'z"],
    ["� Darajam", "🎁 Bonuslar"],
    ["💳 Tariflar", "ℹ️ Aloqa"],
    ["📱 Web App"],
    ["� O'yinlar", "�🏠 Menyu"],
]

ADMIN_MENU_ROWS = [
    ["📊 Dashboard", "💳 To'lovlar", "👥 Userlar"],
    ["📦 Rejalar", "📢 Homiy kanallar", "🎮 O'yinlar"],
    ["📊 Statistika", "📈 Funnel", "🏆 Reyting"],
    ["📄 HTML hisobotlar", "📄 User eksport", "📣 Reklama"],
]

OWNER_ADMIN_EXTRA_ROWS = [
    ["⚙️ To'lov sozlamalari", "ℹ️ Aloqa sozlamalari"],
    ["🎁 Marketing", "👮 Adminlar"],
]

USER_MENU_ALIASES = {
    "tekshiruv": "tekshiruv",
    "tekshirish": "tekshiruv",
    "grammar check": "tekshiruv",
    "check": "tekshiruv",
    "tarjima": "tarjima",
    "translate": "tarjima",
    "translation": "tarjima",
    "talaffuz": "talaffuz",
    "pronunciation": "talaffuz",
    "quiz": "quiz",
    "iq testi": "iq test",
    "iq test": "iq test",
    "iqtest": "iq test",
    "dars": "dars",
    "lesson": "dars",
    "lessons": "dars",
    "grammatika": "grammatika",
    "grammar": "grammatika",
    "kunlik so'z": "kunlik so'z",
    "kunlik soz": "kunlik so'z",
    "daily word": "kunlik so'z",
    "dailyword": "kunlik so'z",
    "darajam": "darajam",
    "reyting": "darajam",
    "darajam / reyting": "darajam",
    "darajam/reyting": "darajam",
    "progress": "darajam",
    "natijalar": "darajam",
    "statistika": "darajam",
    "bonus": "bonuslar",
    "bonuslar": "bonuslar",
    "promo": "bonuslar",
    "o'yinlar": "o'yinlar",
    "oyinlar": "o'yinlar",
    "games": "o'yinlar",
    "game": "o'yinlar",
    "tolovlar": "to'lovlar",
    "to'lovlar": "to'lovlar",
    "payments": "to'lovlar",
    "obuna": "tariflar",
    "tariflar": "tariflar",
    "plans": "tariflar",
    "bosh sahifa": "menyu",
    "home": "menyu",
    "menu": "menyu",
    "menyu": "menyu",
    "aloqa": "aloqa",
    "contact": "aloqa",
    "web app": "web app",
    "webapp": "web app",
    "app": "web app",
    "admin panel": "admin panel",
    "o'rganish": "o'rganish",
    "organish": "o'rganish",
    "o'qish": "o'rganish",
    "oqish": "o'rganish",
    "learn": "o'rganish",
    "study": "o'rganish",
    "mashq": "mashq",
    "mashqlar": "mashq",
    "practice": "mashq",
}

ADMIN_MENU_ALIASES = {
    "admin": "admin panel",
    "admin panel": "admin panel",
    "boshqaruv": "admin panel",
    "dashboard": "dashboard",
    "orqaga": "admin panel",
    "back": "admin panel",
    "payments": "to'lovlar",
    "to'lovlar": "to'lovlar",
    "users": "userlar",
    "foydalanuvchilar": "userlar",
    "userlar": "userlar",
    "analytics": "analitika",
    "analitika": "analitika",
    "stats": "statistika",
    "statistika": "statistika",
    "global statistika": "statistika",
    "sotuv funnel": "funnel",
    "funnel": "funnel",
    "konversiya": "funnel",
    "export": "export users",
    "user eksport": "export users",
    "export users": "export users",
    "foydalanuvchilar eksporti": "export users",
    "foydalanuvchi eksporti": "export users",
    "html hisobot": "html hisobotlar",
    "html hisobotlar": "html hisobotlar",
    "plans": "rejalar",
    "rejalar": "rejalar",
    "sponsors": "homiy kanallar",
    "homiy kanallar": "homiy kanallar",
    "ads": "reklama",
    "reklama": "reklama",
    "owner": "adminlar",
    "adminlar": "adminlar",
    "contact": "aloqa sozlamalari",
    "aloqa sozlamalari": "aloqa sozlamalari",
    "to'lov sozlamalari": "to'lov sozlamalari",
    "marketing": "marketing",
    "reyting": "reyting",
    "o'yinlar": "o'yinlar",
    "oyinlar": "o'yinlar",
    "games": "o'yinlar",
    "user panel": "user panel",
}
